version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: constructpune_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: constructpune_secure_password
      MONGO_INITDB_DATABASE: constructpune_db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - constructpune_network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3

  # ConstructPune Application
  constructpune_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: constructpune_app
    restart: unless-stopped
    environment:
      - MONGO_URL=mongodb://admin:constructpune_secure_password@mongodb:27017/constructpune_db?authSource=admin
      - SECRET_KEY=your-super-secret-key-change-in-production-please
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - ENVIRONMENT=production
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./logs:/var/log/supervisor
      - ./uploads:/app/uploads
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - constructpune_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/api/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis for Caching (Optional)
  redis:
    image: redis:7.2-alpine
    container_name: constructpune_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - constructpune_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Backup Service
  backup:
    image: mongo:7.0
    container_name: constructpune_backup
    restart: "no"
    environment:
      - MONGO_URL=mongodb://admin:constructpune_secure_password@mongodb:27017/constructpune_db?authSource=admin
    volumes:
      - ./backups:/backups
      - ./docker/backup.sh:/backup.sh:ro
    depends_on:
      - mongodb
    networks:
      - constructpune_network
    command: ["sh", "/backup.sh"]

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local

networks:
  constructpune_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16