/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  IsBoolean,
  ValidateNested,
  IsDate,
} from "class-validator";
import { RatingCreateNestedManyWithoutReviewsInput } from "./RatingCreateNestedManyWithoutReviewsInput";
import { Type } from "class-transformer";
import { ToolWhereUniqueInput } from "../../tool/base/ToolWhereUniqueInput";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";

@InputType()
class ReviewCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  body?: string | null;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  published?: boolean | null;

  @ApiProperty({
    required: false,
    type: () => RatingCreateNestedManyWithoutReviewsInput,
  })
  @ValidateNested()
  @Type(() => RatingCreateNestedManyWithoutReviewsInput)
  @IsOptional()
  @Field(() => RatingCreateNestedManyWithoutReviewsInput, {
    nullable: true,
  })
  ratings?: RatingCreateNestedManyWithoutReviewsInput;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  reviewDate?: Date | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  title?: string | null;

  @ApiProperty({
    required: false,
    type: () => ToolWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ToolWhereUniqueInput)
  @IsOptional()
  @Field(() => ToolWhereUniqueInput, {
    nullable: true,
  })
  tool?: ToolWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput | null;
}

export { ReviewCreateInput as ReviewCreateInput };
